# Generated by Django 4.1.7 on 2023-08-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_fooditem_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categry',
            name='category_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='categry',
            name='slug',
            field=models.SlugField(),
        ),
    ]
