# Generated by Django 4.1.7 on 2023-08-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_categry_category_name_alter_categry_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categry',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
